# --------------------------------------------------------------------
# -- Debugging:
# kubectl describe pvc jaeger-pvc
# kubectl get pvc jaeger-pvc
#
#
# -- Delete/Cleanup
# kubectl delete pvc jaeger-pvc;
# --------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: default

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: ''
