# --------------------------------------------------------------------
# -- Debugging:
# kubectl describe pvc jaeger-pvc
# kubectl get events --namespace=default
#
#
# -- Delete/Cleanup
# kubectl delete pvc jaeger-pvc;
# --------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: default
  labels:
    app: jaeger

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: ""
