apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui-deploy
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ui

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: ui

    spec:
      containers:
        - image: foobar:0.0.1

          imagePullPolicy: IfNotPresent
          name: ui

          ports:
            - containerPort: 8080
              name: release-build
              protocol: TCP

          resources:
            requests:
              cpu: 2000m
              memory: 250M

          volumeMounts:
            - mountPath: /app/config
              name: some-default

      volumes:
        - name: some-default
          configMap:
            name: whatever
            items:
              - key: foo.json
                path: foo.json
