apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: deploy.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: my-deploy

resources:
  - base.yaml
