#!/bin/bash

# ---------------------------------------------
# -- Delete go files generated by protoc
# ---------------------------------------------
#set -x # uncomment to debug script
set -e # exit on first error
set -o pipefail
set -u # fail on unset var

# ---------------------------------------------
# -- Constants
# ---------------------------------------------
readonly PARENT_DIR=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")

# ---------------------------------------------
# -- Delete
# ---------------------------------------------
readonly COUNT=$(find "$PARENT_DIR" -name "*.pb.go" | wc -l)

find "$PARENT_DIR" \
  -name "*.pb.go" \
  -print \
  -delete

echo
echo "|-- Successfully deleted $COUNT *.pb.go files"
