# --------------------------------------------------------------------
# NOTE: normally a Sys-admin creates this
#
# Debugging:
# kubectl describe pv
# kubectl get pv
#
#
#
#
#
#
# --------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume-1

spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany

  capacity:
    storage: 8Gi

  claimRef:
    name: foo-pvc
    namespace: foo

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ''
