# Usage: for newline, use multiline string (""") or \n

io.op.bufferedWriter.dart.code = "TODO"
io.op.bufferedWriter.dart.url = "TODO"
io.op.bufferedWriter.go.code = "bufio.NewWriter($EXPR$)"
io.op.bufferedWriter.go.url = "https://pkg.go.dev/bufio#NewWriter"
io.op.bufferedWriter.java.code = "TODO"
io.op.bufferedWriter.java.url = "TODO"
io.op.writeString.dart.code = "TODO"
io.op.writeString.dart.url = "TODO"
io.op.writeString.go.code = "$EXPR$.WriteString(\"foo\")\n$EXPR$.Flush()"
io.op.writeString.go.url = "TODO"
io.op.writeString.java.code = "TODO"
io.op.writeString.java.url = "TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

# --------------------------------------
io.alias = [
    #    ["writeString"],
    ["bufferedWriter", "bufWriter", "bw"],
]


#TODO: absolutePath
#TODO: cleanDir, removeAll
#TODO: copyFile
#TODO: createTempDir, makeTempDir, tempDir
#TODO: delete, remove
#TODO: deleteRecurse, deleteTree
#TODO: exists, fileExists
#TODO: fileContentsEqual, filesEqual
#TODO: fileExtension
#TODO: fileSize, fileLength
#TODO: glob
#TODO: gzipIn, readGzip
#TODO: isDir
#TODO: isRegularFile
#TODO: iterateFiles
#TODO: lines
#TODO: list-files, list
#TODO: matchingFiles
#TODO: mkdir
#TODO: mkdirs
#TODO: mv, rename, move
#TODO: nameWithExtension, filename, name, base
#TODO: nameWithoutExtension
#TODO: normalizePath
#TODO: parent-dir
#TODO: readFile, readToString, readBytes
#TODO: string::reader (postfix)
#TODO: tempFile, createTempFile
#TODO: toBytes, bytes
#TODO: touch
#TODO: truncateFile
#TODO: writeBytes
#TODO: writeGzip, gzipOut
#TODO: writeStrings
