# TODO: bufio.NewWriter(w)

#io..bash.code="TODO"
#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"
#io..kotlin.code="TODO"
#io..python.code="TODO"
#io..rust.code="TODO"
#io..ts.code="TODO"
