# Usage: for newline, use multiline string (""") or \n

io.op.bufferedWriter.dart.code = "TODO"
io.op.bufferedWriter.dart.url = "TODO"
io.op.bufferedWriter.go.code = "bufio.NewWriter($EXPR$)"
io.op.bufferedWriter.go.url = "https://pkg.go.dev/bufio#NewWriter"
io.op.bufferedWriter.java.code = "TODO"
io.op.bufferedWriter.java.url = "TODO"
io.op.writeString.dart.code = "TODO"
io.op.writeString.dart.url = "TODO"
io.op.writeString.go.code = "$EXPR$.WriteString(\"foo\")\n$EXPR$.Flush()"
io.op.writeString.go.url = "TODO"
io.op.writeString.java.code = "TODO"
io.op.writeString.java.url = "TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

#io..dart.code="TODO"
#io..go.code="TODO"
#io..java.code="TODO"

# --------------------------------------
io.alias = [
    #    ["writeString"],
    ["bufferedWriter", "bufWriter", "bw"],
]