lists.op.add.ash.code = "TODO"
lists.op.add.ash.url = "TODO"
lists.op.add.bash.code = "TODO"
lists.op.add.bash.url = "TODO"
lists.op.add.dart.code = "TODO: add"
lists.op.add.dart.url = "https://api.dart.dev/stable/2.16.2/dart-core/List/add.html"
lists.op.add.go.code = "TODO: append-assign"
lists.op.add.go.url = "https://go.dev/ref/spec#Appending_and_copying_slices"
lists.op.add.java.code = "TODO: add"
lists.op.add.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/List.html#add(E)"
lists.op.add.kotlin.code = "TODO: add"
lists.op.add.kotlin.url = "https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-list/add.html"
lists.op.add.python.code = "TODO: append"
lists.op.add.python.url = "https://docs.python.org/3/tutorial/datastructures.html#more-on-lists"
lists.op.add.rust.code = "TODO: push"
lists.op.add.rust.url = "https://doc.rust-lang.org/std/vec/struct.Vec.html#method.push"
lists.op.add.ts.code = "TODO: push"
lists.op.add.ts.url = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push"
lists.op.addAll.ash.code = "TODO"
lists.op.addAll.ash.url = "TODO"
lists.op.addAll.bash.code = "TODO"
lists.op.addAll.bash.url = "TODO"
lists.op.addAll.dart.code = "TODO"
lists.op.addAll.dart.url = "TODO"
lists.op.addAll.go.code = "TODO"
lists.op.addAll.go.url = "TODO"
lists.op.addAll.java.code = "TODO"
lists.op.addAll.java.url = "TODO"
lists.op.addAll.kotlin.code = "TODO"
lists.op.addAll.kotlin.url = "TODO"
lists.op.addAll.python.code = "TODO"
lists.op.addAll.python.url = "TODO"
lists.op.addAll.rust.code = "TODO"
lists.op.addAll.rust.url = "TODO"
lists.op.addAll.ts.code = "TODO"
lists.op.addAll.ts.url = "TODO"
lists.op.clear.ash.code = "TODO"
lists.op.clear.ash.url = "TODO"
lists.op.clear.bash.code = "TODO"
lists.op.clear.bash.url = "TODO"
lists.op.clear.dart.code = "TODO"
lists.op.clear.dart.url = "TODO"
lists.op.clear.go.code = "TODO"
lists.op.clear.go.url = "TODO"
lists.op.clear.java.code = "TODO"
lists.op.clear.java.url = "TODO"
lists.op.clear.kotlin.code = "TODO"
lists.op.clear.kotlin.url = "TODO"
lists.op.clear.python.code = "TODO"
lists.op.clear.python.url = "TODO"
lists.op.clear.rust.code = "TODO"
lists.op.clear.rust.url = "TODO"
lists.op.clear.ts.code = "TODO"
lists.op.clear.ts.url = "TODO"
lists.op.concat.ash.code = "TODO"
lists.op.concat.ash.url = "TODO"
lists.op.concat.bash.code = "TODO"
lists.op.concat.bash.url = "TODO"
lists.op.concat.dart.code = "TODO"
lists.op.concat.dart.url = "TODO"
lists.op.concat.go.code = "TODO"
lists.op.concat.go.url = "TODO"
lists.op.concat.java.code = "TODO"
lists.op.concat.java.url = "TODO"
lists.op.concat.kotlin.code = "TODO"
lists.op.concat.kotlin.url = "TODO"
lists.op.concat.python.code = "TODO"
lists.op.concat.python.url = "TODO"
lists.op.concat.rust.code = "TODO"
lists.op.concat.rust.url = "TODO"
lists.op.concat.ts.code = "TODO"
lists.op.concat.ts.url = "TODO"
lists.op.contains.ash.code = "TODO"
lists.op.contains.ash.url = "TODO"
lists.op.contains.bash.code = "TODO"
lists.op.contains.bash.url = "TODO"
lists.op.contains.dart.code = "TODO"
lists.op.contains.dart.url = "TODO"
lists.op.contains.go.code = "TODO"
lists.op.contains.go.url = "TODO"
lists.op.contains.java.code = "TODO"
lists.op.contains.java.url = "TODO"
lists.op.contains.kotlin.code = "TODO"
lists.op.contains.kotlin.url = "TODO"
lists.op.contains.python.code = "TODO"
lists.op.contains.python.url = "TODO"
lists.op.contains.rust.code = "TODO"
lists.op.contains.rust.url = "TODO"
lists.op.contains.ts.code = "TODO"
lists.op.contains.ts.url = "TODO"
lists.op.equals.ash.code = "TODO"
lists.op.equals.ash.url = "TODO"
lists.op.equals.bash.code = "TODO"
lists.op.equals.bash.url = "TODO"
lists.op.equals.dart.code = "TODO"
lists.op.equals.dart.url = "TODO"
lists.op.equals.go.code = "TODO"
lists.op.equals.go.url = "TODO"
lists.op.equals.java.code = "TODO"
lists.op.equals.java.url = "TODO"
lists.op.equals.kotlin.code = "TODO"
lists.op.equals.kotlin.url = "TODO"
lists.op.equals.python.code = "TODO"
lists.op.equals.python.url = "TODO"
lists.op.equals.rust.code = "TODO"
lists.op.equals.rust.url = "TODO"
lists.op.equals.ts.code = "TODO"
lists.op.equals.ts.url = "TODO"
lists.op.fill.ash.code = "TODO"
lists.op.fill.ash.url = "TODO"
lists.op.fill.bash.code = "TODO"
lists.op.fill.bash.url = "TODO"
lists.op.fill.dart.code = "TODO"
lists.op.fill.dart.url = "TODO"
lists.op.fill.go.code = "TODO"
lists.op.fill.go.url = "TODO"
lists.op.fill.java.code = "TODO"
lists.op.fill.java.url = "TODO"
lists.op.fill.kotlin.code = "TODO"
lists.op.fill.kotlin.url = "TODO"
lists.op.fill.python.code = "TODO"
lists.op.fill.python.url = "TODO"
lists.op.fill.rust.code = "TODO"
lists.op.fill.rust.url = "TODO"
lists.op.fill.ts.code = "TODO"
lists.op.fill.ts.url = "TODO"
lists.op.filter.ash.code = "TODO"
lists.op.filter.ash.url = "TODO"
lists.op.filter.bash.code = "TODO"
lists.op.filter.bash.url = "TODO"
lists.op.filter.dart.code = "TODO"
lists.op.filter.dart.url = "TODO"
lists.op.filter.go.code = "TODO"
lists.op.filter.go.url = "TODO"
lists.op.filter.java.code = "TODO"
lists.op.filter.java.url = "TODO"
lists.op.filter.kotlin.code = "TODO"
lists.op.filter.kotlin.url = "TODO"
lists.op.filter.python.code = "TODO"
lists.op.filter.python.url = "TODO"
lists.op.filter.rust.code = "TODO"
lists.op.filter.rust.url = "TODO"
lists.op.filter.ts.code = "TODO"
lists.op.filter.ts.url = "TODO"
lists.op.fromLiteral.ash.code = "TODO"
lists.op.fromLiteral.ash.url = "TODO"
lists.op.fromLiteral.bash.code = "TODO"
lists.op.fromLiteral.bash.url = "TODO"
lists.op.fromLiteral.dart.code = "TODO"
lists.op.fromLiteral.dart.url = "TODO"
lists.op.fromLiteral.go.code = "TODO"
lists.op.fromLiteral.go.url = "TODO"
lists.op.fromLiteral.java.code = "TODO"
lists.op.fromLiteral.java.url = "TODO"
lists.op.fromLiteral.kotlin.code = "TODO"
lists.op.fromLiteral.kotlin.url = "TODO"
lists.op.fromLiteral.python.code = "TODO"
lists.op.fromLiteral.python.url = "TODO"
lists.op.fromLiteral.rust.code = "TODO"
lists.op.fromLiteral.rust.url = "TODO"
lists.op.fromLiteral.ts.code = "TODO"
lists.op.fromLiteral.ts.url = "TODO"
lists.op.get.ash.code = "TODO"
lists.op.get.ash.url = "TODO"
lists.op.get.bash.code = "TODO"
lists.op.get.bash.url = "TODO"
lists.op.get.dart.code = "TODO"
lists.op.get.dart.url = "TODO"
lists.op.get.go.code = "TODO"
lists.op.get.go.url = "TODO"
lists.op.get.java.code = "TODO"
lists.op.get.java.url = "TODO"
lists.op.get.kotlin.code = "TODO"
lists.op.get.kotlin.url = "TODO"
lists.op.get.python.code = "TODO"
lists.op.get.python.url = "TODO"
lists.op.get.rust.code = "TODO"
lists.op.get.rust.url = "TODO"
lists.op.get.ts.code = "TODO"
lists.op.get.ts.url = "TODO"
lists.op.indexOf.ash.code = "TODO"
lists.op.indexOf.ash.url = "TODO"
lists.op.indexOf.bash.code = "TODO"
lists.op.indexOf.bash.url = "TODO"
lists.op.indexOf.dart.code = "TODO"
lists.op.indexOf.dart.url = "TODO"
lists.op.indexOf.go.code = "TODO"
lists.op.indexOf.go.url = "TODO"
lists.op.indexOf.java.code = "TODO"
lists.op.indexOf.java.url = "TODO"
lists.op.indexOf.kotlin.code = "TODO"
lists.op.indexOf.kotlin.url = "TODO"
lists.op.indexOf.python.code = "TODO"
lists.op.indexOf.python.url = "TODO"
lists.op.indexOf.rust.code = "TODO"
lists.op.indexOf.rust.url = "TODO"
lists.op.indexOf.ts.code = "TODO"
lists.op.indexOf.ts.url = "TODO"
lists.op.isEmpty.ash.code = "TODO"
lists.op.isEmpty.ash.url = "TODO"
lists.op.isEmpty.bash.code = "TODO"
lists.op.isEmpty.bash.url = "TODO"
lists.op.isEmpty.dart.code = "TODO"
lists.op.isEmpty.dart.url = "TODO"
lists.op.isEmpty.go.code = "TODO"
lists.op.isEmpty.go.url = "TODO"
lists.op.isEmpty.java.code = "TODO"
lists.op.isEmpty.java.url = "TODO"
lists.op.isEmpty.kotlin.code = "TODO"
lists.op.isEmpty.kotlin.url = "TODO"
lists.op.isEmpty.python.code = "TODO"
lists.op.isEmpty.python.url = "TODO"
lists.op.isEmpty.rust.code = "TODO"
lists.op.isEmpty.rust.url = "TODO"
lists.op.isEmpty.ts.code = "TODO"
lists.op.isEmpty.ts.url = "TODO"
lists.op.iterator.ash.code = "TODO"
lists.op.iterator.ash.url = "TODO"
lists.op.iterator.bash.code = "TODO"
lists.op.iterator.bash.url = "TODO"
lists.op.iterator.dart.code = "TODO"
lists.op.iterator.dart.url = "TODO"
lists.op.iterator.go.code = "TODO"
lists.op.iterator.go.url = "TODO"
lists.op.iterator.java.code = "TODO"
lists.op.iterator.java.url = "TODO"
lists.op.iterator.kotlin.code = "TODO"
lists.op.iterator.kotlin.url = "TODO"
lists.op.iterator.python.code = "TODO"
lists.op.iterator.python.url = "TODO"
lists.op.iterator.rust.code = "TODO"
lists.op.iterator.rust.url = "TODO"
lists.op.iterator.ts.code = "TODO"
lists.op.iterator.ts.url = "TODO"
lists.op.join.ash.code = "TODO"
lists.op.join.ash.url = "TODO"
lists.op.join.bash.code = "TODO"
lists.op.join.bash.url = "TODO"
lists.op.join.dart.code = "TODO"
lists.op.join.dart.url = "TODO"
lists.op.join.go.code = "TODO"
lists.op.join.go.url = "TODO"
lists.op.join.java.code = "TODO"
lists.op.join.java.url = "TODO"
lists.op.join.kotlin.code = "TODO"
lists.op.join.kotlin.url = "TODO"
lists.op.join.python.code = "TODO"
lists.op.join.python.url = "TODO"
lists.op.join.rust.code = "TODO"
lists.op.join.rust.url = "TODO"
lists.op.join.ts.code = "TODO"
lists.op.join.ts.url = "TODO"
lists.op.new.ash.code = "TODO"
lists.op.new.ash.url = "TODO"
lists.op.new.bash.code = "TODO"
lists.op.new.bash.url = "TODO"
lists.op.new.dart.code = "TODO"
lists.op.new.dart.url = "TODO"
lists.op.new.go.code = "TODO"
lists.op.new.go.url = "TODO"
lists.op.new.java.code = "TODO"
lists.op.new.java.url = "TODO"
lists.op.new.kotlin.code = "TODO"
lists.op.new.kotlin.url = "TODO"
lists.op.new.python.code = "TODO"
lists.op.new.python.url = "TODO"
lists.op.new.rust.code = "TODO"
lists.op.new.rust.url = "TODO"
lists.op.new.ts.code = "TODO"
lists.op.new.ts.url = "TODO"
lists.op.removeLast.ash.code = "TODO"
lists.op.removeLast.ash.url = "TODO"
lists.op.removeLast.bash.code = "TODO"
lists.op.removeLast.bash.url = "TODO"
lists.op.removeLast.dart.code = "TODO"
lists.op.removeLast.dart.url = "TODO"
lists.op.removeLast.go.code = "TODO"
lists.op.removeLast.go.url = "TODO"
lists.op.removeLast.java.code = "TODO"
lists.op.removeLast.java.url = "TODO"
lists.op.removeLast.kotlin.code = "TODO"
lists.op.removeLast.kotlin.url = "TODO"
lists.op.removeLast.python.code = "TODO"
lists.op.removeLast.python.url = "TODO"
lists.op.removeLast.rust.code = "TODO"
lists.op.removeLast.rust.url = "TODO"
lists.op.removeLast.ts.code = "TODO"
lists.op.removeLast.ts.url = "TODO"
lists.op.reverse.ash.code = "TODO"
lists.op.reverse.ash.url = "TODO"
lists.op.reverse.bash.code = "TODO"
lists.op.reverse.bash.url = "TODO"
lists.op.reverse.dart.code = "TODO"
lists.op.reverse.dart.url = "TODO"
lists.op.reverse.go.code = "TODO"
lists.op.reverse.go.url = "TODO"
lists.op.reverse.java.code = "TODO"
lists.op.reverse.java.url = "TODO"
lists.op.reverse.kotlin.code = "TODO"
lists.op.reverse.kotlin.url = "TODO"
lists.op.reverse.python.code = "TODO"
lists.op.reverse.python.url = "TODO"
lists.op.reverse.rust.code = "TODO"
lists.op.reverse.rust.url = "TODO"
lists.op.reverse.ts.code = "TODO"
lists.op.reverse.ts.url = "TODO"
lists.op.shallowCopy.ash.code = "TODO"
lists.op.shallowCopy.ash.url = "TODO"
lists.op.shallowCopy.bash.code = "TODO"
lists.op.shallowCopy.bash.url = "TODO"
lists.op.shallowCopy.dart.code = "TODO"
lists.op.shallowCopy.dart.url = "TODO"
lists.op.shallowCopy.go.code = "TODO"
lists.op.shallowCopy.go.url = "TODO"
lists.op.shallowCopy.java.code = "TODO"
lists.op.shallowCopy.java.url = "TODO"
lists.op.shallowCopy.kotlin.code = "TODO"
lists.op.shallowCopy.kotlin.url = "TODO"
lists.op.shallowCopy.python.code = "TODO"
lists.op.shallowCopy.python.url = "TODO"
lists.op.shallowCopy.rust.code = "TODO"
lists.op.shallowCopy.rust.url = "TODO"
lists.op.shallowCopy.ts.code = "TODO"
lists.op.shallowCopy.ts.url = "TODO"
lists.op.size.ash.code = "TODO"
lists.op.size.ash.url = "TODO"
lists.op.size.bash.code = "TODO"
lists.op.size.bash.url = "TODO"
lists.op.size.dart.code = "TODO"
lists.op.size.dart.url = "TODO"
lists.op.size.go.code = "TODO"
lists.op.size.go.url = "TODO"
lists.op.size.java.code = "TODO"
lists.op.size.java.url = "TODO"
lists.op.size.kotlin.code = "TODO"
lists.op.size.kotlin.url = "TODO"
lists.op.size.python.code = "TODO"
lists.op.size.python.url = "TODO"
lists.op.size.rust.code = "TODO"
lists.op.size.rust.url = "TODO"
lists.op.size.ts.code = "TODO"
lists.op.size.ts.url = "TODO"
lists.op.sort.ash.code = "TODO"
lists.op.sort.ash.url = "TODO"
lists.op.sort.bash.code = "TODO"
lists.op.sort.bash.url = "TODO"
lists.op.sort.dart.code = "TODO"
lists.op.sort.dart.url = "TODO"
lists.op.sort.go.code = "TODO"
lists.op.sort.go.url = "TODO"
lists.op.sort.java.code = "TODO"
lists.op.sort.java.url = "TODO"
lists.op.sort.kotlin.code = "TODO"
lists.op.sort.kotlin.url = "TODO"
lists.op.sort.python.code = "TODO"
lists.op.sort.python.url = "TODO"
lists.op.sort.rust.code = "TODO"
lists.op.sort.rust.url = "TODO"
lists.op.sort.ts.code = "TODO"
lists.op.sort.ts.url = "TODO"
lists.op.sublist.ash.code = "TODO"
lists.op.sublist.ash.url = "TODO"
lists.op.sublist.bash.code = "TODO"
lists.op.sublist.bash.url = "TODO"
lists.op.sublist.dart.code = "TODO"
lists.op.sublist.dart.url = "TODO"
lists.op.sublist.go.code = "TODO"
lists.op.sublist.go.url = "TODO"
lists.op.sublist.java.code = "TODO"
lists.op.sublist.java.url = "TODO"
lists.op.sublist.kotlin.code = "TODO"
lists.op.sublist.kotlin.url = "TODO"
lists.op.sublist.python.code = "TODO"
lists.op.sublist.python.url = "TODO"
lists.op.sublist.rust.code = "TODO"
lists.op.sublist.rust.url = "TODO"
lists.op.sublist.ts.code = "TODO"
lists.op.sublist.ts.url = "TODO"
lists.op.truncate.ash.code = "TODO"
lists.op.truncate.ash.url = "TODO"
lists.op.truncate.bash.code = "TODO"
lists.op.truncate.bash.url = "TODO"
lists.op.truncate.dart.code = "TODO"
lists.op.truncate.dart.url = "TODO"
lists.op.truncate.go.code = "TODO"
lists.op.truncate.go.url = "TODO"
lists.op.truncate.java.code = "TODO"
lists.op.truncate.java.url = "TODO"
lists.op.truncate.kotlin.code = "TODO"
lists.op.truncate.kotlin.url = "TODO"
lists.op.truncate.python.code = "TODO"
lists.op.truncate.python.url = "TODO"
lists.op.truncate.rust.code = "TODO"
lists.op.truncate.rust.url = "https://doc.rust-lang.org/std/vec/struct.Vec.html#method.truncate"
lists.op.truncate.ts.code = "TODO"
lists.op.truncate.ts.url = "TODO"

lists.alias = [
    ["add", "append", "push", "push_back"],
    ["fromLiteral", "literal"],
    ["pop", "removeLast"],
]


#.ash.code = "TODO"
#.ash.url = "TODO"
#.bash.code = "TODO"
#.bash.url = "TODO"
#.dart.code = "TODO"
#.dart.url = "TODO"
#.go.code = "TODO"
#.go.url = "TODO"
#.java.code = "TODO"
#.java.url = "TODO"
#.kotlin.code = "TODO"
#.kotlin.url = "TODO"
#.python.code = "TODO"
#.python.url = "TODO"
#.rust.code = "TODO"
#.rust.url = "TODO"
#.ts.code = "TODO"
#.ts.url = "TODO"