lists.op.add.ash.code = "TODO"
lists.op.add.ash.url = "TODO"
lists.op.add.bash.code = "TODO"
lists.op.add.bash.url = "TODO"
lists.op.add.dart.code = "TODO"
lists.op.add.dart.url = "TODO"
lists.op.add.go.code = "TODO"
lists.op.add.go.url = "TODO"
lists.op.add.java.code = "TODO: add"
lists.op.add.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/List.html#add(E)"
lists.op.add.kotlin.code = "TODO"
lists.op.add.kotlin.url = "TODO"
lists.op.add.python.code = "TODO: append"
lists.op.add.python.url = "https://docs.python.org/3/tutorial/datastructures.html#more-on-lists"
lists.op.add.rust.code = "TODO"
lists.op.add.rust.url = "TODO"
lists.op.add.ts.code = "TODO"
lists.op.add.ts.url = "TODO"

#lists.op.addAll = ""
#lists.op.concat = ""
#lists.op.fill = ""
#lists.op.clear = ""
#lists.op.contains = ""
#lists.op.equals = ""
#lists.op.filter = ""
#lists.op.fromLiteral = ""
#lists.op.get = ""
#lists.op.indexOf = ""
#lists.op.isEmpty = ""
#lists.op.iterator = ""
#lists.op.join = ""
#lists.op.new = ""
#lists.op.removeLast = ""
#lists.op.reverse = ""
#lists.op.shallowCopy = ""
#lists.op.size = ""
#lists.op.sort = ""
#lists.op.sublist = ""

lists.alias = [
]



#.ash.code = "TODO"
#.ash.url = "TODO"
#.bash.code = "TODO"
#.bash.url = "TODO"
#.dart.code = "TODO"
#.dart.url = "TODO"
#.go.code = "TODO"
#.go.url = "TODO"
#.java.code = "TODO"
#.java.url = "TODO"
#.kotlin.code = "TODO"
#.kotlin.url = "TODO"
#.python.code = "TODO"
#.python.url = "TODO"
#.rust.code = "TODO"
#.rust.url = "TODO"
#.ts.code = "TODO"
#.ts.url = "TODO"