strings.contains.dart.code = "TODO"
strings.contains.dart.url = "TODO"
strings.contains.go.code = "TODO"
strings.contains.go.url = "TODO"
strings.contains.java.code = "TODO"
strings.contains.java.url = "TODO"
strings.contains.kotlin.code = "TODO"
strings.contains.kotlin.url = "TODO"
strings.contains.python.code = "TODO"
strings.contains.python.url = "TODO"
strings.contains.rust.code = "TODO"
strings.contains.rust.url = "TODO"
strings.contains.ts.code = "TODO"
strings.contains.ts.url = "TODO"
strings.endswith.dart.code = "TODO"
strings.endswith.dart.url = "TODO"
strings.endswith.go.code = "TODO"
strings.endswith.go.url = "TODO"
strings.endswith.java.code = "TODO"
strings.endswith.java.url = "TODO"
strings.endswith.kotlin.code = "TODO"
strings.endswith.kotlin.url = "TODO"
strings.endswith.python.code = "TODO"
strings.endswith.python.url = "TODO"
strings.endswith.rust.code = "TODO"
strings.endswith.rust.url = "TODO"
strings.endswith.ts.code = "TODO"
strings.endswith.ts.url = "TODO"
strings.equals.dart.code = "TODO"
strings.equals.dart.url = "TODO"
strings.equals.go.code = "TODO"
strings.equals.go.url = "TODO"
strings.equals.java.code = "TODO"
strings.equals.java.url = "TODO"
strings.equals.kotlin.code = "TODO"
strings.equals.kotlin.url = "TODO"
strings.equals.python.code = "TODO"
strings.equals.python.url = "TODO"
strings.equals.rust.code = "TODO"
strings.equals.rust.url = "TODO"
strings.equals.ts.code = "TODO"
strings.equals.ts.url = "TODO"
strings.equalsIgnoreCase.dart.code = "TODO"
strings.equalsIgnoreCase.dart.url = "TODO"
strings.equalsIgnoreCase.go.code = "TODO"
strings.equalsIgnoreCase.go.url = "TODO"
strings.equalsIgnoreCase.java.code = "TODO"
strings.equalsIgnoreCase.java.url = "TODO"
strings.equalsIgnoreCase.kotlin.code = "TODO"
strings.equalsIgnoreCase.kotlin.url = "TODO"
strings.equalsIgnoreCase.python.code = "TODO"
strings.equalsIgnoreCase.python.url = "TODO"
strings.equalsIgnoreCase.rust.code = "TODO"
strings.equalsIgnoreCase.rust.url = "TODO"
strings.equalsIgnoreCase.ts.code = "TODO"
strings.equalsIgnoreCase.ts.url = "TODO"
strings.isBlank.dart.code = "TODO"
strings.isBlank.dart.url = "TODO"
strings.isBlank.go.code = "TODO"
strings.isBlank.go.url = "TODO"
strings.isBlank.java.code = "TODO"
strings.isBlank.java.url = "TODO"
strings.isBlank.kotlin.code = "TODO"
strings.isBlank.kotlin.url = "TODO"
strings.isBlank.python.code = "TODO"
strings.isBlank.python.url = "TODO"
strings.isBlank.rust.code = "TODO"
strings.isBlank.rust.url = "TODO"
strings.isBlank.ts.code = "TODO"
strings.isBlank.ts.url = "TODO"
strings.isEmpty.dart.code = "TODO"
strings.isEmpty.dart.url = "TODO"
strings.isEmpty.go.code = "len($EXPR$) == 0"
strings.isEmpty.go.url = "https://pkg.go.dev/builtin#len"
strings.isEmpty.java.code = "$EXPR$.isEmpty"
strings.isEmpty.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#isEmpty()"
strings.isEmpty.kotlin.code = "TODO"
strings.isEmpty.kotlin.url = "TODO"
strings.isEmpty.python.code = "TODO"
strings.isEmpty.python.url = "TODO"
strings.isEmpty.rust.code = "TODO"
strings.isEmpty.rust.url = "TODO"
strings.isEmpty.ts.code = "TODO"
strings.isEmpty.ts.url = "TODO"
strings.join.dart.code = "TODO"
strings.join.dart.url = "TODO"
strings.join.go.code = "TODO"
strings.join.go.url = "TODO"
strings.join.java.code = "TODO"
strings.join.java.url = "TODO"
strings.join.kotlin.code = "TODO"
strings.join.kotlin.url = "TODO"
strings.join.python.code = "TODO"
strings.join.python.url = "TODO"
strings.join.rust.code = "TODO"
strings.join.rust.url = "TODO"
strings.join.ts.code = "TODO"
strings.join.ts.url = "TODO"
strings.repeat.dart.code = "TODO"
strings.repeat.dart.url = "TODO"
strings.repeat.go.code = "TODO"
strings.repeat.go.url = "TODO"
strings.repeat.java.code = "TODO"
strings.repeat.java.url = "TODO"
strings.repeat.kotlin.code = "TODO"
strings.repeat.kotlin.url = "TODO"
strings.repeat.python.code = "TODO"
strings.repeat.python.url = "TODO"
strings.repeat.rust.code = "TODO"
strings.repeat.rust.url = "TODO"
strings.repeat.ts.code = "TODO"
strings.repeat.ts.url = "TODO"
strings.replaceAll.dart.code = "TODO"
strings.replaceAll.dart.url = "TODO"
strings.replaceAll.go.code = "TODO"
strings.replaceAll.go.url = "TODO"
strings.replaceAll.java.code = "TODO"
strings.replaceAll.java.url = "TODO"
strings.replaceAll.kotlin.code = "TODO"
strings.replaceAll.kotlin.url = "TODO"
strings.replaceAll.python.code = "TODO"
strings.replaceAll.python.url = "TODO"
strings.replaceAll.rust.code = "TODO"
strings.replaceAll.rust.url = "TODO"
strings.replaceAll.ts.code = "TODO"
strings.replaceAll.ts.url = "TODO"
strings.size.dart.code = "TODO"
strings.size.dart.url = "TODO"
strings.size.go.code = "TODO"
strings.size.go.url = "TODO"
strings.size.java.code = "TODO"
strings.size.java.url = "TODO"
strings.size.kotlin.code = "TODO"
strings.size.kotlin.url = "TODO"
strings.size.python.code = "TODO"
strings.size.python.url = "TODO"
strings.size.rust.code = "TODO"
strings.size.rust.url = "TODO"
strings.size.ts.code = "TODO"
strings.size.ts.url = "TODO"
strings.startswith.dart.code = "TODO"
strings.startswith.dart.url = "TODO"
strings.startswith.go.code = "TODO"
strings.startswith.go.url = "TODO"
strings.startswith.java.code = "TODO"
strings.startswith.java.url = "TODO"
strings.startswith.kotlin.code = "TODO"
strings.startswith.kotlin.url = "TODO"
strings.startswith.python.code = "TODO"
strings.startswith.python.url = "TODO"
strings.startswith.rust.code = "TODO"
strings.startswith.rust.url = "TODO"
strings.startswith.ts.code = "TODO"
strings.startswith.ts.url = "TODO"
strings.toLower.dart.code = "TODO"
strings.toLower.dart.url = "TODO"
strings.toLower.go.code = "TODO"
strings.toLower.go.url = "TODO"
strings.toLower.java.code = "TODO"
strings.toLower.java.url = "TODO"
strings.toLower.kotlin.code = "TODO"
strings.toLower.kotlin.url = "TODO"
strings.toLower.python.code = "TODO"
strings.toLower.python.url = "TODO"
strings.toLower.rust.code = "TODO"
strings.toLower.rust.url = "TODO"
strings.toLower.ts.code = "TODO"
strings.toLower.ts.url = "TODO"
strings.toUpper.dart.code = "TODO"
strings.toUpper.dart.url = "TODO"
strings.toUpper.go.code = "TODO"
strings.toUpper.go.url = "TODO"
strings.toUpper.java.code = "TODO"
strings.toUpper.java.url = "TODO"
strings.toUpper.kotlin.code = "TODO"
strings.toUpper.kotlin.url = "TODO"
strings.toUpper.python.code = "TODO"
strings.toUpper.python.url = "TODO"
strings.toUpper.rust.code = "TODO"
strings.toUpper.rust.url = "TODO"
strings.toUpper.ts.code = "TODO"
strings.toUpper.ts.url = "TODO"
strings.trim.dart.code = "TODO"
strings.trim.dart.url = "TODO"
strings.trim.go.code = "TODO"
strings.trim.go.url = "TODO"
strings.trim.java.code = "TODO"
strings.trim.java.url = "TODO"
strings.trim.kotlin.code = "TODO"
strings.trim.kotlin.url = "TODO"
strings.trim.python.code = "TODO"
strings.trim.python.url = "TODO"
strings.trim.rust.code = "TODO"
strings.trim.rust.url = "TODO"
strings.trim.ts.code = "TODO"
strings.trim.ts.url = "TODO"


#| [String::`charAt`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#charAt(int)) | `"abc"[i:i+1]` or `( []rune("abc") )[3] == 'd'`| TODO |
#| [String::`compareTo`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#compareTo(java.lang.String)) |`s1 < s2` or [`strings.Compare(...)`](https://pkg.go.dev/strings#Compare) | TODO |
#| [String::`contains`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#contains(java.lang.CharSequence)) |[`strings.Contains(haystack, needle)`](https://pkg.go.dev/strings#Contains) | TODO |
#| [String::`endsWith`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#endsWith(java.lang.String)) | [`strings.HasSuffix(s, sfx)`](https://pkg.go.dev/strings#HasSuffix) | TODO |
#| [String::`equals`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#equals(java.lang.Object)) |`s1 == s2`| TODO |
#| [String::`equalsIgnoreCase`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#equalsIgnoreCase(java.lang.String)) | [`strings.EqualsFold(s1, s2)`](https://pkg.go.dev/strings#EqualFold) | TODO |
#| [String::`format`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object...)) | [`fmt.Sprintf(s, ...)`](https://pkg.go.dev/fmt#Sprintf) | TODO |
#| [String::`getBytes`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#getBytes()) |`[]byte(s)`| TODO |
#| [String::`indexOf`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#indexOf(int)) | [`strings.Index(haystack, needle)`](https://pkg.go.dev/strings#Index) | TODO |
#| [String::`isBlank`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()) |[`strings.TrimSpace(s) == ""`](https://pkg.go.dev/strings#TrimSpace) | TODO |
#| [String::`lastIndexOf`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#lastIndexOf(int)) | [`strings.LastIndex(haystack, needle)`](https://pkg.go.dev/strings#LastIndex) | TODO |
#| [String::`length`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#length()) | [`len(s)`](https://pkg.go.dev/builtin#len) | TODO |
#| [String::`repeat`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#repeat(int)) | [`strings.Repeat(s, n)`](https://pkg.go.dev/strings#Repeat) | TODO |
#| [String::`replaceAll`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#replaceAll(java.lang.String,java.lang.String)) | [`strings.ReplaceAll(...)`](https://pkg.go.dev/strings#ReplaceAll) | TODO |
#| [String::`split`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#split(java.lang.String)) | [`strings.Split(s, sep)`](https://pkg.go.dev/strings#Split) | TODO |
#| [String::`startsWith`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#startsWith(java.lang.String)) | [`strings.HasPrefix(s, pfx)`](https://pkg.go.dev/strings#HasPrefix) | TODO |
#| [String::`substring`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#substring(int,int)) |`"abcde"[2:4] == "cd"`| TODO |
#| [String::`toCharArray`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toCharArray()) |Use range in loops, or `[]rune(s)`| TODO |
#| [String::`toLowerCase`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toLowerCase()) | [`strings.ToLower(s)`](https://pkg.go.dev/strings#ToLower) | TODO |
#| [String::`toUpperCase`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toUpperCase()) | [`strings.ToUpper(s)`](https://pkg.go.dev/strings#ToUpper) | TODO |
#| [String::`trim`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#trim()) |[`strings.TrimSpace(s)`](https://pkg.go.dev/strings#TrimSpace) | TODO |
#| [String::`valueOf`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#valueOf(java.lang.Object)) |`string(foo)`| TODO |
#| [StringUtils::`join`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#join-java.lang.Iterable-java.lang.String-) | [`strings.Join(slice, sep)`](https://pkg.go.dev/strings#Join) | TODO |
#| [StringUtils::containsAny](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#containsAny-java.lang.CharSequence-char...-) | [`strings.ContainsAny(haystack,needles)`](https://pkg.go.dev/strings#ContainsAny) | TODO |
