strings.bytes.dart.code = "$EXPR$.runes"
strings.bytes.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/runes.html"
strings.bytes.go.code = "[]byte($EXPR$)"
strings.bytes.go.url = "TODO"
strings.bytes.java.code = '$EXPR$.getBytes("UTF8")'
strings.bytes.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#getBytes(java.lang.String)"
strings.bytes.kotlin.code = "TODO"
strings.bytes.kotlin.url = "TODO"
strings.bytes.python.code = "TODO"
strings.bytes.python.url = "TODO"
strings.bytes.rust.code = "$EXPR$.as_bytes()"
strings.bytes.rust.url = "https://doc.rust-lang.org/std/string/struct.String.html#method.as_bytes"
strings.bytes.ts.code = "TODO"
strings.bytes.ts.url = "TODO"
strings.charAt.dart.code = "$EXPR$[3]"
strings.charAt.dart.url = ""
strings.charAt.go.code = "$EXPR$[i:i+1] /* or */ ( []rune($EXPR$) )[3]"
strings.charAt.go.url = ""
strings.charAt.java.code = "$EXPR$.charAt(3)"
strings.charAt.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#charAt(int)"
strings.charAt.kotlin.code = "TODO"
strings.charAt.kotlin.url = "TODO"
strings.charAt.python.code = "$EXPR$[3]"
strings.charAt.python.url = "TODO"
strings.charAt.rust.code = "$EXPR$.chars().nth(3)"
strings.charAt.rust.url = "https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.nth"
strings.charAt.ts.code = "TODO"
strings.charAt.ts.url = "TODO"
strings.chars.dart.code = "$EXPR$.split('')"
strings.chars.dart.url = "https://api.flutter.dev/flutter/dart-core/String/split.html"
strings.chars.go.code = "range in $EXPR$ /* or */ []rune($EXPR$)"
strings.chars.go.url = "TODO"
strings.chars.java.code = "$EXPR$.toCharArray()"
strings.chars.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toCharArray()"
strings.chars.kotlin.code = "TODO"
strings.chars.kotlin.url = "TODO"
strings.chars.python.code = "TODO"
strings.chars.python.url = "TODO"
strings.chars.rust.code = "$EXPR$.chars()"
strings.chars.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.chars"
strings.chars.ts.code = "TODO"
strings.chars.ts.url = "TODO"
strings.compareTo.dart.code = "$EXPR$.compareTo(s2)"
strings.compareTo.dart.url = "https://api.flutter.dev/flutter/dart-core/String/compareTo.html"
strings.compareTo.go.code = "strings.Compare($EXPR$, s2)"
strings.compareTo.go.url = "https://pkg.go.dev/strings#Compare"
strings.compareTo.java.code = "$EXPR$.compareTo(s2)"
strings.compareTo.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#compareTo(java.lang.String)"
strings.compareTo.kotlin.code = "TODO"
strings.compareTo.kotlin.url = "TODO"
strings.compareTo.python.code = "$EXPR$ < s2"
strings.compareTo.python.url = ""
strings.compareTo.rust.code = "$EXPR$.cmp(s2) == Ordering::Less"
strings.compareTo.rust.url = "https://doc.rust-lang.org/std/cmp/trait.Ord.html#tymethod.cmp"
strings.compareTo.ts.code = "TODO"
strings.compareTo.ts.url = "TODO"
strings.contains.dart.code = "$EXPR$.contains(needle)"
strings.contains.dart.url = "https://api.dart.dev/stable/2.17.0/dart-core/String/contains.html"
strings.contains.go.code = "strings.Contains($EXPR$, needle)"
strings.contains.go.url = "https://pkg.go.dev/strings#Contains"
strings.contains.java.code = "$EXPR$.contains(needle)"
strings.contains.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#contains(java.lang.CharSequence)"
strings.contains.kotlin.code = "TODO"
strings.contains.kotlin.url = "TODO"
strings.contains.python.code = "needle in $EXPR$"
strings.contains.python.url = "https://docs.python.org/3/library/operator.html#mapping-operators-to-functions"
strings.contains.rust.code = "$EXPR$.contains(needle)"
strings.contains.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.contains"
strings.contains.ts.code = "TODO"
strings.contains.ts.url = "TODO"
strings.endsWith.dart.code = "$EXPR$.endsWith(sfx)"
strings.endsWith.dart.url = "https://api.dart.dev/stable/2.17.0/dart-core/String/endsWith.html"
strings.endsWith.go.code = "strings.HasSuffix($EXPR$, sfx)"
strings.endsWith.go.url = "https://pkg.go.dev/strings#HasSuffix"
strings.endsWith.java.code = "$EXPR$.endsWith(sfx)"
strings.endsWith.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#endsWith(java.lang.String)"
strings.endsWith.kotlin.code = "TODO"
strings.endsWith.kotlin.url = "TODO"
strings.endsWith.python.code = "$EXPR$.endswith(sfx)"
strings.endsWith.python.url = "https://docs.python.org/3/library/stdtypes.html?highlight=endswith#str.endswith"
strings.endsWith.rust.code = "$EXPR$.ends_with(sfx)"
strings.endsWith.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.ends_with"
strings.endsWith.ts.code = "TODO"
strings.endsWith.ts.url = "TODO"
strings.equals.dart.code = "$EXPR$ == s2"
strings.equals.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/operator_equals.html"
strings.equals.go.code = "$EXPR$ == s2"
strings.equals.go.url = "https://go.dev/ref/spec#Comparison_operators"
strings.equals.java.code = '$EXPR$.equals(s2)'
strings.equals.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#equals(java.lang.Object)"
strings.equals.kotlin.code = "TODO"
strings.equals.kotlin.url = "TODO"
strings.equals.python.code = "$EXPR$ == s2"
strings.equals.python.url = "https://docs.python.org/3/library/operator.html?highlight=operator#operator.eq"
strings.equals.rust.code = "$EXPR$ == s2"
strings.equals.rust.url = "https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#tymethod.eq"
strings.equals.ts.code = "TODO"
strings.equals.ts.url = "TODO"
strings.equalsIgnoreCase.dart.code = "$EXPR$.toLowerCase() == s2.toLowerCase()"
strings.equalsIgnoreCase.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/toLowerCase.html"
strings.equalsIgnoreCase.go.code = "strings.EqualsFold($EXPR$, s2)"
strings.equalsIgnoreCase.go.url = "https://pkg.go.dev/strings#EqualFold"
strings.equalsIgnoreCase.java.code = "$EXPR$.equalsIgnoreCase(s2)"
strings.equalsIgnoreCase.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#equalsIgnoreCase(java.lang.String)"
strings.equalsIgnoreCase.kotlin.code = "TODO"
strings.equalsIgnoreCase.kotlin.url = "TODO"
strings.equalsIgnoreCase.python.code = "TODO"
strings.equalsIgnoreCase.python.url = "TODO"
strings.equalsIgnoreCase.rust.code = "$EXPR$.eq_ignore_ascii_case(&s2)"
strings.equalsIgnoreCase.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.eq_ignore_ascii_case"
strings.equalsIgnoreCase.ts.code = "TODO"
strings.equalsIgnoreCase.ts.url = "TODO"
strings.indexOf.dart.code = "$EXPR$.indexOf(needle)"
strings.indexOf.dart.url = "https://api.dart.dev/be/181224/dart-core/String/indexOf.html"
strings.indexOf.go.code = "strings.Index(haystack, needle)"
strings.indexOf.go.url = "https://pkg.go.dev/strings#Index"
strings.indexOf.java.code = "$EXPR$.indexOf(needle)"
strings.indexOf.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#indexOf(int)"
strings.indexOf.kotlin.code = "TODO"
strings.indexOf.kotlin.url = "TODO"
strings.indexOf.python.code = "TODO"
strings.indexOf.python.url = "TODO"
strings.indexOf.rust.code = "$EXPR$.find(needle)"
strings.indexOf.rust.url = "https://doc.rust-lang.org/std/string/struct.String.html#method.find"
strings.indexOf.ts.code = "TODO"
strings.indexOf.ts.url = "TODO"
strings.isBlank.dart.code = "$EXPR$.trim().isEmpty"
strings.isBlank.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/Iterable/isEmpty.html"
strings.isBlank.go.code = 'strings.TrimSpace(s) == ""'
strings.isBlank.go.url = "https://pkg.go.dev/strings#TrimSpace"
strings.isBlank.java.code = "$EXPR$.isBlank()"
strings.isBlank.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()"
strings.isBlank.kotlin.code = "TODO"
strings.isBlank.kotlin.url = "TODO"
strings.isBlank.python.code = '$EXPR$.strip() == ""'
strings.isBlank.python.url = "https://docs.python.org/3/library/stdtypes.html#str.strip"
strings.isBlank.rust.code = '$EXPR$.trim() == ""'
strings.isBlank.rust.url = "TODO"
strings.isBlank.ts.code = "TODO"
strings.isBlank.ts.url = "TODO"
strings.isEmpty.dart.code = "$EXPR$.isEmpty"
strings.isEmpty.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/isEmpty.html"
strings.isEmpty.go.code = "len($EXPR$) == 0"
strings.isEmpty.go.url = "https://pkg.go.dev/builtin#len"
strings.isEmpty.java.code = "$EXPR$.isEmpty"
strings.isEmpty.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#isEmpty()"
strings.isEmpty.kotlin.code = "TODO"
strings.isEmpty.kotlin.url = "TODO"
strings.isEmpty.python.code = '$EXPR$ == ""'
strings.isEmpty.python.url = "https://docs.python.org/3/library/stdtypes.html#comparisons"
strings.isEmpty.rust.code = "$EXPR$ == s2"
strings.isEmpty.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.is_empty"
strings.isEmpty.ts.code = "TODO"
strings.isEmpty.ts.url = "TODO"
strings.join.dart.code = '$EXPR$.join(",")'
strings.join.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/Iterable/join.html"
strings.join.go.code = "strings.Join(slice, sep)"
strings.join.go.url = "https://pkg.go.dev/strings#Join"
strings.join.java.code = 'String.join(" ", List.of("a", "b", "c"))'
strings.join.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#join(java.lang.CharSequence,java.lang.Iterable)"
strings.join.kotlin.code = "TODO"
strings.join.kotlin.url = "TODO"
strings.join.python.code = "TODO"
strings.join.python.url = "https://docs.python.org/3/library/stdtypes.html#str.join"
strings.join.rust.code = 'vec!["a", "b", "c"].join(sep)'
strings.join.rust.url = "https://doc.rust-lang.org/std/primitive.slice.html#method.join"
strings.join.ts.code = "TODO"
strings.join.ts.url = "TODO"
strings.lastIndexOf.dart.code = "$EXPR$.lastIndexOf(needle)"
strings.lastIndexOf.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/lastIndexOf.html"
strings.lastIndexOf.go.code = "strings.LastIndex(haystack, needle)"
strings.lastIndexOf.go.url = "https://pkg.go.dev/strings#LastIndex"
strings.lastIndexOf.java.code = "$EXPR$.lastIndexOf(needle)"
strings.lastIndexOf.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#lastIndexOf(int)"
strings.lastIndexOf.kotlin.code = "TODO"
strings.lastIndexOf.kotlin.url = "TODO"
strings.lastIndexOf.python.code = "TODO"
strings.lastIndexOf.python.url = "TODO"
strings.lastIndexOf.rust.code = "$EXPR$.rfind(needle)"
strings.lastIndexOf.rust.url = "https://doc.rust-lang.org/std/string/struct.String.html#method.rfind"
strings.lastIndexOf.ts.code = "TODO"
strings.lastIndexOf.ts.url = "TODO"
strings.length.dart.code = "$EXPR$.length"
strings.length.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/length.html"
strings.length.go.code = "len($EXPR$)"
strings.length.go.url = "https://pkg.go.dev/builtin#len"
strings.length.java.code = "$EXPR$.length()"
strings.length.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#length()"
strings.length.kotlin.code = "TODO"
strings.length.kotlin.url = "TODO"
strings.length.python.code = "TODO"
strings.length.python.url = "TODO"
strings.length.rust.code = "$EXPR$.len()"
strings.length.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.len"
strings.length.ts.code = "TODO"
strings.length.ts.url = "TODO"
strings.repeat.dart.code = "$EXPR$ * n"
strings.repeat.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/operator_multiply.html"
strings.repeat.go.code = "strings.Repeat(s, n)"
strings.repeat.go.url = "https://pkg.go.dev/strings#Repeat"
strings.repeat.java.code = "$EXPR$.repeat(n)"
strings.repeat.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#repeat(int)"
strings.repeat.kotlin.code = "TODO"
strings.repeat.kotlin.url = "TODO"
strings.repeat.python.code = "TODO"
strings.repeat.python.url = "TODO"
strings.repeat.rust.code = "$EXPR$.repeat(n)"
strings.repeat.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.repeat"
strings.repeat.ts.code = "TODO"
strings.repeat.ts.url = "TODO"
strings.replaceAll.dart.code = "$EXPR$.replaceAll(RegExp(r'ab'), new)"
strings.replaceAll.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/replaceAll.html"
strings.replaceAll.go.code = "strings.ReplaceAll($EXPR$, old, new)"
strings.replaceAll.go.url = "https://pkg.go.dev/strings#ReplaceAll"
strings.replaceAll.java.code = "$EXPR$.replaceAll(old, new)"
strings.replaceAll.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#replaceAll(java.lang.String,java.lang.String)"
strings.replaceAll.kotlin.code = "TODO"
strings.replaceAll.kotlin.url = "TODO"
strings.replaceAll.python.code = "TODO"
strings.replaceAll.python.url = "TODO"
strings.replaceAll.rust.code = "$EXPR$.replace(old, new)"
strings.replaceAll.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.replace"
strings.replaceAll.ts.code = "TODO"
strings.replaceAll.ts.url = "TODO"
strings.split.dart.code = "$EXPR$.split(sep)"
strings.split.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/split.html"
strings.split.go.code = "strings.Split(s, sep)"
strings.split.go.url = "https://pkg.go.dev/strings#Split"
strings.split.java.code = "$EXPR$.split(sep, 0)"
strings.split.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#split(java.lang.String)"
strings.split.kotlin.code = "TODO"
strings.split.kotlin.url = "TODO"
strings.split.python.code = "TODO"
strings.split.python.url = "TODO"
strings.split.rust.code = 'let v: Vec<_> = "$EXPR$".split(sep).collect()'
strings.split.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.split"
strings.split.ts.code = "TODO"
strings.split.ts.url = "TODO"
strings.startsWith.dart.code = "$EXPR$.startsWith(pfx)"
strings.startsWith.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/startsWith.html"
strings.startsWith.go.code = "strings.HasPrefix($EXPR$, pfx)"
strings.startsWith.go.url = "https://pkg.go.dev/strings#HasPrefix"
strings.startsWith.java.code = "$EXPR$.startsWith(pfx)"
strings.startsWith.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#startsWith(java.lang.String)"
strings.startsWith.kotlin.code = "TODO"
strings.startsWith.kotlin.url = "TODO"
strings.startsWith.python.code = "TODO"
strings.startsWith.python.url = "TODO"
strings.startsWith.rust.code = "$EXPR$.starts_with(pfx)"
strings.startsWith.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.starts_with"
strings.startsWith.ts.code = "TODO"
strings.startsWith.ts.url = "TODO"
strings.substring.dart.code = "$EXPR$.substring(start, end)"
strings.substring.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/substring.html"
strings.substring.go.code = '"abcde"[2:4] == "cd"'
strings.substring.go.url = "TODO"
strings.substring.java.code = '"abcde".substring(2, 4).equals("cd")'
strings.substring.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#substring(int,int)"
strings.substring.kotlin.code = "TODO"
strings.substring.kotlin.url = "TODO"
strings.substring.python.code = "TODO"
strings.substring.python.url = "TODO"
strings.substring.rust.code = '&"abcde"[2..4] == "cd"'
strings.substring.rust.url = "https://doc.rust-lang.org/nightly/book/ch08-02-strings.html#slicing-strings"
strings.substring.ts.code = "TODO"
strings.substring.ts.url = "TODO"
strings.toLower.dart.code = "$EXPR$.toLowerCase()"
strings.toLower.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/toLowerCase.html"
strings.toLower.go.code = "strings.ToLower($EXPR$)"
strings.toLower.go.url = "https://pkg.go.dev/strings#ToLower"
strings.toLower.java.code = "$EXPR$.toLowerCase(Locale.ROOT)"
strings.toLower.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toLowerCase()"
strings.toLower.kotlin.code = "TODO"
strings.toLower.kotlin.url = "TODO"
strings.toLower.python.code = "TODO"
strings.toLower.python.url = "TODO"
strings.toLower.rust.code = "$EXPR$.to_lowercase()"
strings.toLower.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.to_lowercase"
strings.toLower.ts.code = "TODO"
strings.toLower.ts.url = "TODO"
strings.toUpper.dart.code = "$EXPR$.toUpperCase()"
strings.toUpper.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/toUpperCase.html"
strings.toUpper.go.code = "strings.ToUpper($EXPR$)"
strings.toUpper.go.url = "https://pkg.go.dev/strings#ToUpper"
strings.toUpper.java.code = "$EXPR$.toUpperCase(Locale.ROOT)"
strings.toUpper.java.url = "https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toUpperCase()"
strings.toUpper.kotlin.code = "TODO"
strings.toUpper.kotlin.url = "TODO"
strings.toUpper.python.code = "TODO"
strings.toUpper.python.url = "TODO"
strings.toUpper.rust.code = "$EXPR$.to_uppercase()"
strings.toUpper.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.to_uppercase"
strings.toUpper.ts.code = "TODO"
strings.toUpper.ts.url = "TODO"
strings.trim.dart.code = "$EXPR$.trim()"
strings.trim.dart.url = "https://api.dart.dev/stable/2.17.6/dart-core/String/trim.html"
strings.trim.go.code = "strings.TrimSpace($EXPR$)"
strings.trim.go.url = "https://pkg.go.dev/strings#TrimSpace"
strings.trim.java.code = "$EXPR$.strip()"
strings.trim.java.url = "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#strip()"
strings.trim.kotlin.code = "TODO"
strings.trim.kotlin.url = "TODO"
strings.trim.python.code = "TODO"
strings.trim.python.url = "TODO"
strings.trim.rust.code = "$EXPR$.trim()"
strings.trim.rust.url = "https://doc.rust-lang.org/std/primitive.str.html#method.trim"
strings.trim.ts.code = "TODO"
strings.trim.ts.url = "TODO"


#strings..dart.code="TODO"
#strings..go.code="TODO"
#strings..java.code="TODO"
#strings..kotlin.code="TODO"
#strings..python.code="TODO"
#strings..rust.code="TODO"
#strings..ts.code="TODO"

# TODO: [String::`format`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object...)) | [`fmt.Sprintf(s, ...)`](https://pkg.go.dev/fmt#Sprintf) | TODO |
# TODO: [String::`valueOf`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#valueOf(java.lang.Object)) |`string(foo)`| TODO |
