# --------------------------------------------------------------------
# -- Debugging:
# kubectl describe cm postgres-cm --namespace=default
# kubectl get cm postgres-cm
# --------------------------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: postgres
  name: postgres-cm
  namespace: default

data:
  # -- Default database name
  POSTGRES_DB: "postgres"

  # -- superuser name
  POSTGRES_USER: "postgres"

# TODO: db conf:
#data:
#  postgresql.conf: |
#    max_connections = 100
#    shared_buffers = 256MB
#    log_statement = 'all'