# --------------------------------------------------------------------
# -- Debugging:
# kubectl describe pvc postgres-pvc
# kubectl get events --namespace=default
#
# kubectl logs --selector app=adminer
#
# -- Delete/Cleanup
# kubectl delete pvc postgres-pvc;
# --------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
    group: db
  name: postgres-pvc
  namespace: default

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: ""
