# --------------------------------------------------------------------
# -- Debugging:
#
# kubectl describe secret postgres-secret
# kubectl get secret postgres-secret
# --------------------------------------------------------------------

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres
    group: db
  name: postgres-secret
  namespace: default

data:
  # -- Base64 encode: echo -n 'Zz612l7amMZNXigH0ED' | base64
  postgres-password: "Wno2MTJsN2FtTVpOWGlnSDBFRA=="

type: Opaque
