# --------------------------------------------------------------------
# NOTE: normally a Sys-admin creates this
#
#
# -- Add
# kubectl apply -f ./local.pv.yaml
#
#
# -- Debugging:
# kubectl describe pv
# kubectl describe pv my-volume-1
#
# ls -hl /tmp/volume-for-minikube-1
# du -h /tmp/volume-for-minikube-1
#
#
# -- Remove/Delete
# kubectl delete pv my-volume-1
#
# --------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolume

metadata:
  name: my-volume-1

spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  local:
    path: /tmp/volume-for-minikube-1

#  persistentVolumeReclaimPolicy: Delete
  persistentVolumeReclaimPolicy: Retain

  storageClassName: standard
  volumeMode: Filesystem

  # -- Only required for Local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - wc-box-02
                # TODO: add other hostnames here